### ISSUE TITLE
Create a Lexicon

### ISSUE THREAD

**Issue by una** [opensourcedesign/slick#2]
A shared vocabulary of terms for all designers/devs/content strategists/etc. to refer to

**Comment by bnvk** [comment]
@una interesting to better understand what you mean in this context. Care to elaborate? :)

**Comment by GarthDB** [comment]
I think one of the main goals is to establish a glossary of terms that we use frequently use and with their definitions so we can be on the same page when discussing topics.

**Comment by bnvk** [comment]
@GarthDB right, I get the need for disambiguation, but like what words are particularly ambiguous / causing issues? What scope of words are talking about? Does this pertain to chat specifically?

Feel free to post things and create a list of terms :)

**Comment by jdittrich** [comment]
@winterdamsel may know more about this. 

As far as I know from our research, there are often communication barriers between devs and designers. This seems to be only partly caused by lack of common words. Different values and experiences may play a large role too.  

What I would suggest is some sort of "how to understand … better" with a list of common tools which programmers/designers use, and what typical values/misunderstandings are. (It may get us a bit into stereotype space though)

**Comment by bnvk** [comment]
Migrated this to website repo. Thanks for the nice idea @una :)
